<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KONTAKTI</name>
   <tag></tag>
   <elementGuidId>cca51888-24b1-4a82-9500-f54ed6600afb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7d3e68c-f57d-4871-b56a-c70136650138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/aplikacije/kontakti/</value>
      <webElementGuid>e403afbe-4ac6-4de1-8744-d5820abbb8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KONTAKTI</value>
      <webElementGuid>0552d73d-2dba-405a-8c9f-dd7e3e912577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/div[@class=&quot;block&quot;]/ul[1]/li[5]/a[1]</value>
      <webElementGuid>1e62bd31-df76-4c1b-8d4e-1852fd69192a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      <webElementGuid>1513be9d-71da-4486-9be0-9bbba5f19d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'KONTAKTI')])[2]</value>
      <webElementGuid>fe7af564-fd7d-4093-9a58-53c6e96f30a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKADEMIJA FERI'])[2]/following::a[1]</value>
      <webElementGuid>1a0d61b4-dbe7-4bdb-a8bd-3d1e91d8b102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAZISKOVANJE'])[2]/following::a[2]</value>
      <webElementGuid>19e248d2-782c-40b7-9926-76cc39041ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zapri primarno navigacijo'])[1]/preceding::a[1]</value>
      <webElementGuid>ce7dfb51-9113-48a3-b5cf-75038ab7468c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOVICE'])[1]/preceding::a[2]</value>
      <webElementGuid>deb466eb-f210-4a6b-b42a-d008a5a3c42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/aplikacije/kontakti/')])[2]</value>
      <webElementGuid>5c8b1518-d9ed-4db2-84da-5909120d8209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/div/ul/li[5]/a</value>
      <webElementGuid>f6766e72-722b-4653-ae1c-9cc7833bc5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/aplikacije/kontakti/' and (text() = 'KONTAKTI' or . = 'KONTAKTI')]</value>
      <webElementGuid>07dbfe0e-da35-4eb3-b6e1-9370a08cff82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
